
### IP ADDRESS: localhost 
### GET ALL
GET http://localhost:8081/sql_api/all_users

### GET ONE
GET http://localhost:8081/sql_api/user?un=ID

### PUT
PUT http://localhost:8081/sql_api/user/:id
Content-Type: application/json

{
    
}

### DELETE
DELETE http://localhost:8081/sql_api/user/:id
Content-Type: application/json

{
    
}

###POST CREATE USER
POST http://localhost:8081/sql_api/user
Content-Type: application/json

{
	"un": "",
	"password": ""
}

###POST CHECK USER
POST http://localhost:8081/login
Content-Type: application/json

{
	"un": "",
	"password": ""
}
